import pandas as pd
import re
import os
# Aortic Disease Keywords
aortic_keywords = [
    # Diseases/Conditions
    r'\baorta\b',
    r'\baortic\b',
    r'\bacute aortic syndrome\b',
    r'\baortic dissection\b',
    r'\bdissection, abdominal aorta\b',
    r'\babdominal\b',
    r'\babdominal aorta\b',
    r'\babdominal aortic\b',
    r'\babdominal aortic dissection\b',
    r'\bdissection, thoracoabdominal aorta\b',
    r'\bthoracoabdominal aortic dissection\b',
    r'\bdissection, thoracic aorta\b',
    r'\baortic arch dissection\b',
    r'\barch\b',
    r'\barch aneurysm\b',
    r'\bdescending aorta dissection\b',
    r'\bdescending thoracic aortic dissection\b',
    r'\bdissection, aortic arch\b',
    r'\bdissection, descending aorta\b',
    r'\bdissection, descending thoracic aorta\b',
    r'\bthoracic aorta dissection\b',
    r'\bthoracic aortic dissection\b',
    r'\baortic intramural hematoma\b',
    r'\bintramural hematoma aorta\b',
    r'\bpenetrating atherosclerotic ulcer\b',
    r'\baortic penetrating ulcer\b',
    r'\bpenetrating aortic ulcer\b',
    r'\bpenetrating ulcer\b',
    r'\bpenetrating ulcer aorta\b',
    r'\baortic aneurysm\b',
    r'\baortic aneurysm, abdominal\b',
    r'\babdominal aorta aneurysm\b',
    r'\babdominal aortic aneurysm\b',
    r'\baneurysm, abdominal aorta\b',
    r'\baneurysm, abdominal aortic\b',
    r'\baortic aneurysm, thoracoabdominal\b',
    r'\btaa thoracoabdominal aortic aneurysm\b',
    r'\bthoracoabdominal aortic aneurysm\b',
    r'\baortic aneurysm, thoracic\b',
    r'\baneurysm, aortic arch\b',
    r'\baortic arch aneurysm\b',
    r'\baortic root aneurysm\b',
    r'\baneurysm, aortic root\b',
    r'\baneurysm, ascending aorta\b',
    r'\baaa ascending aorta aneurysm\b',
    r'\bascending aorta aneurysm\b',
    r'\bascending aortic aneurysm\b',
    r'\bdescending thoracic aortic aneurysm\b',
    r'\baneurysm, descending thoracic aorta\b',
    r'\baneurysm, thoracic aorta\b',
    r'\baneurysm, thoracic aortic\b',
    r'\bthoracic aorta aneurysm\b',
    r'\bthoracic aortic aneurysm\b',
    r'\baortic rupture\b',
    r'\baortic aneurysm, ruptured\b',
    r'\bruptured aortic aneurysm\b',
    r'\bloeys-dietz syndrome\b',
    r'\bloeys-dietz aortic aneurysm syndrome\b',
    r'\bloeys-dietz syndrome, type 1a\b',
    r'\bmarfan syndrome\b',
    r'\baortic arch syndromes\b',
    r'\btakayasu arteritis\b',
    r'\baortitis syndrome\b',
    r'\barteritis, takayasu\'?s\b',
    r'\bpulseless disease\b',
    r'\btakayasu disease\b',
    r'\btakayasu syndrome\b',
    r'\btakayasu\'?s arteritis\b',
    r'\byoung female arteritis\b',
    r'\bvascular ring\b',
    r'\bdouble aortic arch\b',
    r'\bright aortic arch syndrome\b',
    r'\bright aortic arch with left ligamentum arteriosum\b',
    r'\baortitis\b',
    r'\bleriche\'?s syndrome\b',
    r'\baortic valve disease\b',
    r'\bAneurysm\b',
    r'\bAneurysm, Infected\b',
    r'\bAneurysms, Infected\b',
    r'\bInfected Aneurysms\b',
    r'\bInfected Aneurysm\b',
    r'\bAneurysm, Bacterial\b',
    r'\bAneurysms, Bacterial\b',
    r'\bBacterial Aneurysm\b',
    r'\bBacterial Aneurysms\b',
    r'\bAneurysm, Mycotic\b',
    r'\bAneurysms, Mycotic\b',
    r'\bMycotic Aneurysms\b',
    r'\bMycotic Aneurysm\b',
    r'\bFungal Aneurysm\b',
    r'\bAneurysm, Fungal\b',
    r'\bAneurysms, Fungal\b',
    r'\bFungal Aneurysms\b',
    r'\bAneurysm, Ruptured\b',
    r'\bAneurysms, Ruptured\b',
    r'\bRuptured Aneurysms\b',
    r'\bRuptured Aneurysm\b',
    r'\bAortic Rupture\b',
    r'\bAortic Ruptures\b',
    r'\bRupture, Aortic\b',
    r'\bRuptures, Aortic\b',
    r'\bAortic Aneurysm, Ruptured\b',
    r'\bAneurysm, Ruptured Aortic\b',
    r'\bAneurysms, Ruptured Aortic\b',
    r'\bAortic Aneurysms, Ruptured\b',
    r'\bRuptured Aortic Aneurysms\b',
    r'\bRuptured Aortic Aneurysm\b',
    
    # Aortic Procedures
    r'\baortic valve procedures\b',
    r'\baortic valve replacement\b',
    r'\bavr\b',
    r'\btranscatheter aortic valve replacement\b',
    r'\btavr\b',
    r'\baortic valve repair\b',
    r'\bross procedure\b',
    r'\bvalve-sparing aortic root replacement\b',
    r'\bdavid procedure\b',
    r'\byacoub procedure\b',
    r'\baortic root replacement\b',
    r'\bascending aorta replacement\b',
    r'\baortic arch repair\b',
    r'\baortic arch replacement\b',
    r'\bdescending thoracic aorta repair\b',
    r'\bdescending thoracic aorta replacement\b',
    r'\bthoracoabdominal aortic aneurysm repair\b',
    r'\btaaa repair\b',
    r'\babdominal aortic aneurysm repair\b',
    r'\baaa repair\b',
    r'\btevar\b',
    r'\bevar\b',
    r'\bfevar\b',
    r'\baortocaval fistula repair\b',
    r'\baortoenteric fistula repair\b',
    r'\bceliac artery bypass\b',
    r'\bmesenteric artery bypass\b',
    r'\brenal artery bypass\b',
    r'\brenal artery endarterectomy\b',
    r'\bstenting to repair aneurysms\b',
    r'\bopen aortic repair\b',
    r'\bhybrid aortic repair\b',
    r'\bdebranching\b',
    r'\baortic reconstruction\b',
    r'\baortic surgery\b',
    r'\baortic repair\b',
    r'\baortic replacement\b',
    r'\baortic graft\b',
    r'\baortography\b',
    r'\bendoleak\b',
    r'\bendoleaks\b',
    r'\bendograft\b',
    r'\bendografts\b',
]

# Cerebrovascular Disease Keywords
cerebrovascular_keywords = [
    # Diseases/Conditions
    r'\bcerebrovascular diseases\b',
    r'\bcerebrovascular\b',
    r'\bcerebral\b',
    r'\bbasal ganglia cerebrovascular disease\b',
    r'\bbasal ganglia vascular disease\b',
    r'\bcerebrovascular disease, basal ganglia\b',
    r'\blenticulostriate diseases, vascular\b',
    r'\blenticulostriate vascular diseases\b',
    r'\blenticulostriate vasculopathy\b',
    r'\bvascular disease, basal ganglia\b',
    r'\bvascular diseases, basal ganglia\b',
    r'\bvascular diseases, lenticulostriate\b',
    r'\bbasal ganglia hemorrhage\b',
    r'\bbasal ganglionic hemorrhage\b',
    r'\bhematoma, basal ganglia\b',
    r'\bhemorrhage, basal ganglia\b',
    r'\bputaminal hemorrhage\b',
    r'\bbrain hemorrhage, putaminal\b',
    r'\bhemorrhage, putamen\b',
    r'\bputaminal hematoma\b',
    r'\bbrain ischemia\b',
    r'\bcerebral ischemia\b',
    r'\bencephalopathy, ischemic\b',
    r'\bishemia, cerebral\b',
    r'\bischemic encephalopathy\b',
    r'\bbrain infarction\b',
    r'\banterior cerebral circulation infarction\b',
    r'\banterior circulation brain infarction\b',
    r'\banterior circulation infarction, brain\b',
    r'\bbrain infarct\b',
    r'\bbrain infarction, anterior circulation\b',
    r'\bbrain infarction, posterior circulation\b',
    r'\bbrain infarction, venous\b',
    r'\binfarction, anterior cerebral circulation\b',
    r'\binfarction, anterior circulation, brain\b',
    r'\binfarction, brain, anterior circulation\b',
    r'\binfarction, brain, posterior circulation\b',
    r'\binfarction, posterior circulation, brain\b',
    r'\bposterior circulation brain infarction\b',
    r'\bposterior circulation infarction, brain\b',
    r'\bvenous infarction, brain\b',
    r'\bbrain stem infarctions\b',
    r'\bbenedict syndrome\b',
    r'\bbrain stem infarct\b',
    r'\bbrainstem infarctions\b',
    r'\bbrainstem stroke\b',
    r'\bclaude syndrome\b',
    r'\bfoville syndrome\b',
    r'\binfarctions, brain stem\b',
    r'\binfarctions, brainstem\b',
    r'\bmillard-gublar syndrome\b',
    r'\btop of the basilar syndrome\b',
    r'\bweber syndrome\b',
    r'\blateral medullary syndrome\b',
    r'\bdorsolateral medullary syndrome\b',
    r'\blateral bulbar syndrome\b',
    r'\bposterior inferior cerebellar artery syndrome\b',
    r'\bvieseaux-wallenberg syndrome\b',
    r'\bwallenberg syndrome\b',
    r'\bwallenberg\'?s syndrome\b',
    r'\bcerebral infarction\b',
    r'\banterior choroidal artery infarction\b',
    r'\bcerebral infarct\b',
    r'\bcerebral infarction, left hemisphere\b',
    r'\bcerebral infarction, right hemisphere\b',
    r'\bcerebral, left hemisphere, infarction\b',
    r'\bcerebral, right hemisphere, infarction\b',
    r'\binfarction, cerebral\b',
    r'\binfarction, cerebral, left hemisphere\b',
    r'\binfarction, cerebral, right hemisphere\b',
    r'\binfarction, left hemisphere, cerebral\b',
    r'\binfarction, right hemisphere, cerebral\b',
    r'\bleft hemisphere, cerebral infarction\b',
    r'\bleft hemisphere, infarction, cerebral\b',
    r'\bposterior choroidal artery infarction\b',
    r'\bright hemisphere, cerebral infarction\b',
    r'\bright hemisphere, infarction, cerebral\b',
    r'\bsubcortical infarction\b',
    r'\bcadasil\b',
    r'\bcadasilm\b',
    r'\bcerebral arteriopathy with subcortical infarcts and leukoencephalopathy\b',
    r'\bcerebral autosomal dominant arteriopathy with subcortical infarcts and leukoencephalopathy\b',
    r'\bdementia, hereditary multi-infarct type\b',
    r'\bdementia, multi-infarct\b',
    r'\bdementia multi-infarct\b',
    r'\bdementia, multiinfarct\b',
    r'\blacunar dementia\b',
    r'\blacunar dementias\b',
    r'\bmulti-infarct dementia\b',
    r'\binfarction, anterior cerebral artery\b',
    r'\baca infarct\b',
    r'\baca infarction\b',
    r'\banterior cerebral artery infarction\b',
    r'\banterior cerebral artery stroke\b',
    r'\banterior cerebral artery syndrome\b',
    r'\bheubner artery infarction\b',
    r'\bheubner\'?s artery infarction\b',
    r'\binfarction, anterior cerebral artery circulation\b',
    r'\binfarction, anterior cerebral artery distribution\b',
    r'\binfarction, heubner artery\b',
    r'\bstroke, anterior cerebral artery\b',
    r'\bsyndrome, anterior cerebral artery\b',
    r'\binfarction, middle cerebral artery\b',
    r'\bcerebral infarction, middle cerebral artery\b',
    r'\bembolic infarction, middle cerebral artery\b',
    r'\bembolus, middle cerebral artery\b',
    r'\bleft middle cerebral artery infarction\b',
    r'\bmca infarct\b',
    r'\bmca infarction\b',
    r'\bmiddle cerebral artery circulation infarction\b',
    r'\bmiddle cerebral artery embolic infarction\b',
    r'\bmiddle cerebral artery embolus\b',
    r'\bmiddle cerebral artery infarction\b',
    r'\bmiddle cerebral artery occlusion\b',
    r'\bmiddle cerebral artery stroke\b',
    r'\bmiddle cerebral artery syndrome\b',
    r'\bmiddle cerebral artery thrombosis\b',
    r'\bmiddle cerebral artery thrombotic infarction\b',
    r'\bocclusion, middle cerebral artery\b',
    r'\bright middle cerebral artery infarction\b',
    r'\bstroke, middle cerebral artery\b',
    r'\bthrombosis, middle cerebral artery\b',
    r'\bthrombotic infarction, middle cerebral artery\b',
    r'\binfarction, posterior cerebral artery\b',
    r'\bembolic infarction, posterior cerebral artery\b',
    r'\bpca infarct\b',
    r'\bpca infarction\b',
    r'\bposterior cerebral artery embolic infarction\b',
    r'\bposterior cerebral artery infarction\b',
    r'\bposterior cerebral artery stroke\b',
    r'\bposterior cerebral artery syndrome\b',
    r'\bposterior cerebral artery thrombotic infarction\b',
    r'\bstroke, posterior cerebral artery\b',
    r'\bthrombotic infarction, posterior cerebral artery\b',
    r'\bhypoxia-ischemia, brain\b',
    r'\banoxia-ischemia, brain\b',
    r'\banoxia-ischemia, cerebral\b',
    r'\banoxic-ischemic encephalopathy\b',
    r'\bbrain anoxia-ischemia\b',
    r'\bbrain hypoxia-ischemia\b',
    r'\bbrain ischemia-anoxia\b',
    r'\bbrain ischemia-hypoxia\b',
    r'\bcerebral anoxia-ischemia\b',
    r'\bcerebral hypoxia-ischemia\b',
    r'\bcerebral ischemia-anoxia\b',
    r'\bcerebral ischemia-hypoxia\b',
    r'\bencephalopathy, anoxic-ischemic\b',
    r'\bencephalopathy, hypoxic-ischemic\b',
    r'\bhypoxia-ischemia, cerebral\b',
    r'\bhypoxic-ischemic encephalopathy\b',
    r'\bischemia-anoxia, brain\b',
    r'\bischemia-anoxia, cerebral\b',
    r'\bischemia-hypoxia, brain\b',
    r'\bischemia-hypoxia, cerebral\b',
    r'\bischemic-hypoxic encephalopathy\b',
    r'\bischemic attack, transient\b',
    r'\banterior circulation transient ischemic attack\b',
    r'\bbrain stem ischemia, transient\b',
    r'\bbrain stem transient ischemic attack\b',
    r'\bbrain tia\b',
    r'\bbrainstem ischemia, transient\b',
    r'\bbrainstem transient ischemic attack\b',
    r'\bcarotid circulation transient ischemic attack\b',
    r'\bcerebral ischemia, transient\b',
    r'\bcrescendo transient ischemic attacks\b',
    r'\bposterior circulation transient ischemic attack\b',
    r'\btia\b',
    r'\btransient ischemic attack\b',
    r'\btransient ischemic attack, anterior circulation\b',
    r'\btransient ischemic attack, brain stem\b',
    r'\btransient ischemic attack, brainstem\b',
    r'\btransient ischemic attack, carotid circulation\b',
    r'\btransient ischemic attack, posterior circulation\b',
    r'\btransient ischemic attack, vertebrobasilar circulation\b',
    r'\bvertebrobasilar circulation transient ischemic attack\b',
    r'\bvertebrobasilar insufficiency\b',
    r'\bbasilar artery insufficiency\b',
    r'\bbasilar artery ischemia\b',
    r'\bbasilar artery stenosis\b',
    r'\bbasilar insufficiency\b',
    r'\bvertebral artery insufficiency\b',
    r'\bvertebral artery ischemia\b',
    r'\bvertebral artery stenosis\b',
    r'\bvertebro-basilar insufficiency\b',
    r'\bvertebro-basilar ischemia\b',
    r'\bvertebrobasilar dolichoectasia\b',
    r'\bvertebrobasilar ischemia\b',
    r'\bsubclavian steal syndrome\b',
    r'\bbasilar steal syndrome\b',
    r'\bbrachial-basilar insufficiency syndrome\b',
    r'\bsubclavian artery stenosis\b',
    r'\bsubclavian steal\b',
    r'\bsubclavian steal phenomenon\b',
    r'\bsubclavian-carotid artery steal syndrome\b',
    r'\bcarotid artery diseases\b',
    r'\bcarotid\b',
    r'\barterial diseases, carotid\b',
    r'\barterial diseases, common carotid\b',
    r'\barterial diseases, external carotid\b',
    r'\barterial diseases, internal carotid\b',
    r'\batherosclerotic disease, carotid\b',
    r'\bcarotid artery disorders\b',
    r'\bcarotid atherosclerosis\b',
    r'\bcarotid atherosclerotic disease\b',
    r'\bcommon carotid artery disease\b',
    r'\bcommon carotid artery diseases\b',
    r'\bexternal carotid artery diseases\b',
    r'\binternal carotid artery disease\b',
    r'\binternal carotid artery diseases\b',
    r'\bcarotid artery injuries\b',
    r'\bcarotid arteriopathies, traumatic\b',
    r'\bcarotid false aneurysm\b',
    r'\bcarotid pseudoaneurysm\b',
    r'\bfalse aneurysm, carotid\b',
    r'\binjuries, carotid artery\b',
    r'\btrauma, carotid artery\b',
    r'\bcarotid artery, internal, dissection\b',
    r'\bcarotid artery dissection, internal\b',
    r'\bdissection, internal carotid artery\b',
    r'\binternal carotid artery dissection\b',
    r'\bcarotid artery thrombosis\b',
    r'\bcarotid thrombosis\b',
    r'\bcommon carotid artery thrombosis\b',
    r'\bexternal carotid artery thrombosis\b',
    r'\binternal carotid artery thrombosis\b',
    r'\bthrombosis, carotid\b',
    r'\bthrombosis, carotid artery\b',
    r'\bthrombosis, common carotid artery\b',
    r'\bthrombosis, external carotid artery\b',
    r'\bthrombosis, internal carotid artery\b',
    r'\bcarotid-cavernous sinus fistula\b',
    r'\bc-c fistula\b',
    r'\bcaroticocavernous fistula\b',
    r'\bcarotid artery-cavernous sinus fistula\b',
    r'\bcarotid cavernous fistula\b',
    r'\bfistula, carotid artery-cavernous sinus\b',
    r'\btraumatic carotid-cavernous sinus fistula\b',
    r'\bcarotid stenosis\b',
    r'\bcarotid artery narrowing\b',
    r'\bcarotid artery plaque\b',
    r'\bcarotid artery stenosis\b',
    r'\bcarotid artery ulcerating plaque\b',
    r'\bcarotid ulcer\b',
    r'\bcommon carotid artery stenosis\b',
    r'\bexternal carotid artery stenosis\b',
    r'\binternal carotid artery stenosis\b',
    r'\bplaque, ulcerating, carotid artery\b',
    r'\bstenosis, common carotid artery\b',
    r'\bstenosis, external carotid artery\b',
    r'\bulcerating plaque, carotid artery\b',
    r'\bmoyamoya disease\b',
    r'\bcerebrovascular moyamoya disease\b',
    r'\bmoya-moya disease\b',
    r'\bmoyamoya disease, classic\b',
    r'\bmoyamoya disease, primary\b',
    r'\bmoyamoya disease, secondary\b',
    r'\bmoyamoya syndrome\b',
    r'\bprogressive intracranial occlusive arteropathy \(moyamoya\)\b',
    r'\bcerebral small vessel diseases\b',
    r'\bcerebral microangiopathies\b',
    r'\bcerebral small vessel disease\b',
    r'\bcerebral amyloid angiopathy, familial\b',
    r'\bamyloidosis vi\b',
    r'\bamyloidosis, cerebroarterial, icelandic type\b',
    r'\bautosomal dominant cerebrovascular amyloidosis\b',
    r'\bcerebral amyloid angiopathy, cst3-related\b',
    r'\bcerebral amyloid angiopathy, genetic\b',
    r'\bcerebral amyloid angiopathy, hereditary\b',
    r'\bcerebral hemorrhage, hereditary, with amyloidosis\b',
    r'\bfamilial cerebral amyloid angiopathy\b',
    r'\bhchwa\b',
    r'\bhereditary cerebral amyloid angiopathy\b',
    r'\bhereditary cerebral amyloid angiopathy, icelandic type\b',
    r'\bhereditary cerebral hemorrhage with amyloidosis\b',
    r'\bicelandic type amyloidosis\b',
    r'\bicelandic type hereditary cerebral amyloid angiopathy\b',
    r'\bfabry disease\b',
    r'\banderson-fabry disease\b',
    r'\bangiokeratoma corporis diffusum\b',
    r'\bangiokeratoma diffuse\b',
    r'\bangiokeratoma, diffuse\b',
    r'\bceramide trihexosidase deficiency\b',
    r'\bfabry\'?s disease\b',
    r'\bgla deficiency\b',
    r'\bhereditary dystopic lipidosis\b',
    r'\balpha-galactosidase a deficiency\b',
    r'\balpha-galactosidase a deficiency disease\b',
    r'\bmelas syndrome\b',
    r'\bmelas\b',
    r'\bmitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes\b',
    r'\bmitochondrial myopathy, encephalopathy, lactic acidosis, and stroke-like episodes\b',
    r'\bmitochondrial myopathy, lactic acidosis, stroke-like episode\b',
    r'\bmyopathy, mitochondrial-encephalopathy-lactic acidosis-stroke\b',
    r'\bmicroscopic polyangiitis\b',
    r'\bstroke, lacunar\b',
    r'\binfarct, lacunar\b',
    r'\binfarction, lacunar\b',
    r'\blacunar syndrome\b',
    r'\bcerebrovascular trauma\b',
    r'\bbrain injury, vascular\b',
    r'\binjury, vascular, brain\b',
    r'\bvascular injury, brain\b',
    r'\bvascular trauma, brain\b',
    r'\bsubarachnoid hemorrhage, traumatic\b',
    r'\bpost-traumatic subarachnoid hemorrhage\b',
    r'\btraumatic subarachnoid hemorrhage\b',
    r'\bvertebral artery dissection\b',
    r'\bdissecting vertebral artery aneurysm\b',
    r'\bspontaneous vertebral artery dissection\b',
    r'\btraumatic vertebral artery dissection\b',
    r'\bvertebral artery dissection, spontaneous\b',
    r'\bvertebral artery dissection, traumatic\b',
    r'\bintracranial arterial diseases\b',
    r'\barterial brain diseases\b',
    r'\barterial diseases, brain\b',
    r'\barterial diseases, intracranial\b',
    r'\bbrain diseases, arterial\b',
    r'\bbrain disorders, arterial\b',
    r'\bintracranial arterial disorders\b',
    r'\bintracranial aneurysm\b',
    r'\baneurysm, anterior cerebral artery\b',
    r'\baneurysm, anterior communicating artery\b',
    r'\baneurysm, basilar artery\b',
    r'\baneurysm, cerebral\b',
    r'\baneurysm, intracranial\b',
    r'\baneurysm, middle cerebral artery\b',
    r'\baneurysm, posterior cerebral artery\b',
    r'\baneurysm, posterior communicating artery\b',
    r'\banterior cerebral artery aneurysm\b',
    r'\banterior communicating artery aneurysm\b',
    r'\bbasilar artery aneurysm\b',
    r'\bberry aneurysm\b',
    r'\bbrain aneurysm\b',
    r'\bcerebral aneurysm\b',
    r'\bgiant intracranial aneurysm\b',
    r'\bmiddle cerebral artery aneurysm\b',
    r'\bmycotic aneurysm, intracranial\b',
    r'\bposterior cerebral artery aneurysm\b',
    r'\bposterior communicating artery aneurysm\b',
    r'\bintracranial arteriosclerosis\b',
    r'\bcerebral arteriosclerosis\b',
    r'\bcerebral atherosclerosis\b',
    r'\bintracranial atherosclerosis\b',
    r'\bdementia, vascular\b',
    r'\bacute onset vascular dementia\b',
    r'\barteriosclerotic dementia\b',
    r'\barteriosclerotic encephalopathy, subcortical\b',
    r'\bbinswanger disease\b',
    r'\bbinswanger encephalopathy\b',
    r'\bbinswanger\'?s disease\b',
    r'\bchronic progressive subcortical encephalopathy\b',
    r'\bencephalopathy, binswanger\b',
    r'\bencephalopathy, binswanger\'?s\b',
    r'\bencephalopathy, chronic progressive subcortical\b',
    r'\bencephalopathy, subcortical arteriosclerotic\b',
    r'\bencephalopathy, subcortical, chronic progressive\b',
    r'\bleukoencephalopathy, subcortical\b',
    r'\bsubcortical arteriosclerotic encephalopathy\b',
    r'\bsubcortical encephalopathy, chronic progressive\b',
    r'\bsubcortical leukoencephalopathy\b',
    r'\bsubcortical vascular dementia\b',
    r'\bvascular dementia\b',
    r'\bvascular dementia, acute onset\b',
    r'\bintracranial arteriovenous malformations\b',
    r'\bavm \(arteriovenous malformation\) intracranial\b',
    r'\barteriovenous malformations, cerebral\b',
    r'\bcerebral arteriovenous malformations\b',
    r'\bcongenital intracranial arteriovenous malformations\b',
    r'\bintracranial arteriovenous malformation, ruptured\b',
    r'\bintracranial arteriovenous malformations, congenital\b',
    r'\bruptured intracranial arteriovenous malformation\b',
    r'\bvein of galen malformations\b',
    r'\bvein of galen malformation\b',
    r'\bintracranial embolism and thrombosis\b',
    r'\bbrain embolism and thrombosis\b',
    r'\bcerebral embolism and thrombosis\b',
    r'\bembolism and thrombosis, brain\b',
    r'\bintracranial embolism\b',
    r'\bbrain emboli\b',
    r'\bbrain embolism\b',
    r'\bcerebral emboli\b',
    r'\bcerebral embolism\b',
    r'\bembolism, brain\b',
    r'\bembolism, intracranial\b',
    r'\bintracranial thrombosis\b',
    r'\bbrain thrombosis\b',
    r'\bbrain thrombus\b',
    r'\bcerebral thrombosis\b',
    r'\bcerebral thrombus\b',
    r'\bthrombosis, brain\b',
    r'\bthrombosis, intracranial\b',
    r'\bthrombus, intracranial\b',
    r'\bsinus thrombosis, intracranial\b',
    r'\bcranial sinus thrombosis\b',
    r'\bintracranial sinus thrombophlebitis\b',
    r'\bpetrous sinus thrombophlebitis\b',
    r'\bpetrous sinus thrombosis\b',
    r'\bsinus thrombosis\b',
    r'\bvenous sinus thrombosis, cranial\b',
    r'\bcavernous sinus thrombosis\b',
    r'\bcavernous sinus thrombophlebitis\b',
    r'\bcavernous sinus, phlebitis, septic\b',
    r'\bcaverous sinus septic phlebitis\b',
    r'\bphlebitis, cavernous sinus, septic\b',
    r'\bseptic cavernous sinusitis\b',
    r'\bseptic phlebitis, cavernous sinus\b',
    r'\bthrombosis, cavernous sinus\b',
    r'\blateral sinus thrombosis\b',
    r'\blateral sinus thrombophlebitis\b',
    r'\bphlebitis, lateral sinus, septic\b',
    r'\bseptic phlebitis, lateral sinus\b',
    r'\bthrombosis, lateral sinus\b',
    r'\btransverse sinus thrombosis\b',
    r'\bsagittal sinus thrombosis\b',
    r'\bphlebitis, sagittal sinus, septic\b',
    r'\bsagittal sinus septic phlebitis\b',
    r'\bsagittal sinus thrombophlebitis\b',
    r'\bseptic phlebitis, sagittal sinus\b',
    r'\bthrombosis, sagittal sinus\b',
    r'\bintracranial hemorrhages\b',
    r'\bbrain hemorrhage\b',
    r'\bhemorrhage, intracranial\b',
    r'\bposterior fossa hemorrhage\b',
    r'\bcerebral hemorrhage\b',
    r'\bbrain hemorrhage, cerebral\b',
    r'\bcerebral parenchymal hemorrhage\b',
    r'\bhemorrhage, cerebral\b',
    r'\bhemorrhage, cerebrum\b',
    r'\bintracerebral hemorrhage\b',
    r'\bcerebral intraventricular hemorrhage\b',
    r'\bcerebral intraventricular haemorrhage\b',
    r'\bintracranial hemorrhage, hypertensive\b',
    r'\bcerebral hemorrhage, hypertensive\b',
    r'\bhypertensive hemorrhage, cerebral\b',
    r'\bhypertensive hemorrhage, intracranial\b',
    r'\bintracerebral hemorrhage, hypertensive\b',
    r'\bintracranial hemorrhage, traumatic\b',
    r'\bhemorrhage, intracranial, traumatic\b',
    r'\bintracranial hematoma, traumatic\b',
    r'\btraumatic intracranial hemorrhage\b',
    r'\bbrain hemorrhage, traumatic\b',
    r'\bcerebellar hemorrhage, traumatic\b',
    r'\btraumatic brain hemorrhage\b',
    r'\bbrain stem hemorrhage, traumatic\b',
    r'\bbrain stem hematoma, traumatic\b',
    r'\bbrain stem hemorrhage, post-traumatic\b',
    r'\bbrainstem hematoma, traumatic\b',
    r'\bbrainstem hemorrhage, traumatic\b',
    r'\bbulbar hemorrhage, traumatic\b',
    r'\bhemorrhage, brain stem, traumatic\b',
    r'\bmedullary hemorrhage, traumatic\b',
    r'\bmidbrain hemorrhage, traumatic\b',
    r'\bpontine hemorrhage, traumatic\b',
    r'\bpost-traumatic brain stem hemorrhage\b',
    r'\bpost-traumatic brainstem hemorrhage\b',
    r'\btraumatic brain stem hematoma\b',
    r'\btraumatic brain stem hemorrhage\b',
    r'\btraumatic brainstem hemorrhage\b',
    r'\bhematoma, epidural, cranial\b',
    r'\bcranial epidural hematoma\b',
    r'\bepidural hemorrhage, cranial\b',
    r'\bextradural hematoma, cranial\b',
    r'\bextradural hemorrhage, cranial\b',
    r'\bhematoma, epidural, intracranial\b',
    r'\bhemorrhage, cranial epidural\b',
    r'\bintracranial epidural hematoma\b',
    r'\bhematoma, subdural\b',
    r'\bhemorrhage, subdural\b',
    r'\bsubdural hematoma\b',
    r'\bsubdural hematoma, traumatic\b',
    r'\bhematoma, subdural, acute\b',
    r'\bhemorrhage, subdural, acute\b',
    r'\bsubdural hematoma, acute\b',
    r'\bhematoma, subdural, chronic\b',
    r'\bhemorrhage, subdural, chronic\b',
    r'\bsubdural hematoma, chronic\b',
    r'\bhematoma, subdural, intracranial\b',
    r'\bhematoma, subdural, cranial\b',
    r'\bintracranial subdural hematoma\b',
    r'\bintracranial subdural hematoma, traumatic\b',
    r'\bsubdural hematoma, traumatic, intracranial\b',
    r'\btraumatic intracranial subdural hematoma\b',
    r'\bpituitary apoplexy\b',
    r'\bapoplexy, pituitary\b',
    r'\bsubarachnoid hemorrhage\b',
    r'\bhemorrhage, subarachnoid\b',
    r'\bperinatal subarachnoid hemorrhage\b',
    r'\bsah\b',
    r'\bsubarachnoid hemorrhage, aneurysmal\b',
    r'\bsubarachnoid hemorrhage, intracranial\b',
    r'\bsubarachnoid hemorrhage, spontaneous\b',
    r'\bleukomalacia, periventricular\b',
    r'\bcystic periventricular leukomalacia\b',
    r'\bencephalomalacia, periventricular\b',
    r'\bleucomalacia, periventricular\b',
    r'\bneonatal cerebral leukomalacia\b',
    r'\bperiventricular leukomalacia\b',
    r'\bsneddon syndrome\b',
    r'\blivedo reticularis and cerebrovascular accidents\b',
    r'\blivedo reticularis, systemic involvement\b',
    r'\bsneddon-champion syndrome\b',
    r'\bstroke\b',
    r'\bapoplexy\b',
    r'\bcva\b',
    r'\bcerebral stroke\b',
    r'\bcerebrovascular accident\b',
    r'\bcerebrovascular accident, acute\b',
    r'\bcerebrovascular apoplexy\b',
    r'\bcerebrovascular stroke\b',
    r'\bstroke, acute\b',
    r'\bvascular accident, brain\b',
    r'\bhemorrhagic stroke\b',
    r'\bintracerebral hemorrhage stroke\b',
    r'\bintracerebral hemorrhagic stroke\b',
    r'\bsubarachnoid hemorrhagic stroke\b',
    r'\bischemic stroke\b',
    r'\bacute ischemic stroke\b',
    r'\bcryptogenic embolism stroke\b',
    r'\bcryptogenic ischemic stroke\b',
    r'\bcryptogenic stroke\b',
    r'\bischaemic stroke\b',
    r'\bwake-up stroke\b',
    r'\bembolic stroke\b',
    r'\bcardio-embolic stroke\b',
    r'\bcardioembolic stroke\b',
    r'\bthrombotic stroke\b',
    r'\bacute thrombotic stroke\b',
    r'\bvascular depression\b',
    r'\bsubcortical ischemic depression\b',
    r'\bvascular headaches\b',
    r'\bcephalgia, vascular\b',
    r'\bheadache, vascular\b',
    r'\bvascular headache\b',
    r'\bvasculitis, central nervous system\b',
    r'\bangiitis, central nervous system\b',
    r'\bcns vasculitis\b',
    r'\bcentral nervous system angiitis\b',
    r'\bcentral nervous system vasculitis\b',
    r'\bcerebral angiitis\b',
    r'\bcerebral vasculitis\b',
    r'\bgranulomatous angiitis\b',
    r'\bgranulomatous arteritis\b',
    r'\bpostzoster arteritis\b',
    r'\bprimary cns vasculitis\b',
    r'\bprimary central nervous system vasculitis\b',
    r'\bsecondary cns vasculitis\b',
    r'\bvasculitis, cns, secondary\b',
    r'\baids arteritis, central nervous system\b',
    r'\baids-associated cerebral aneurysmal arteriopathy\b',
    r'\bcns vasculitis, hiv-associated\b',
    r'\bcentral nervous system aids arteritis\b',
    r'\bcerebral aneurysmal arteriopathy, aids-associated\b',
    r'\bhiv-1-associated cns vasculitis\b',
    r'\bhiv-associated vasculitis of the central nervous system\b',
    r'\bvasculitis of the central nervous system, hiv-associated\b',
    r'\bgiant cell arteritis\b',
    r'\baortic arteritis, giant cell\b',
    r'\baortitis, giant cell\b',
    r'\barteritis, giant cell, horton\b',
    r'\barteritis, giant cell, horton\'?s\b',
    r'\barteritis, temporal\b',
    r'\bcranial arteritis\b',
    r'\bgiant cell aortic arteritis\b',
    r'\bgiant cell aortitis\b',
    r'\bgiant cell aortitis, horton\'?s\b',
    r'\bgiant cell arteritis, horton\b',
    r'\bhorton disease\b',
    r'\bhorton giant cell arteritis\b',
    r'\bhorton\'?s disease\b',
    r'\bhorton\'?s giant cell arteritis\b',
    r'\bjuvenile temporal arteritis\b',
    r'\btemporal arteritis\b',
    r'\blupus vasculitis, central nervous system\b',
    r'\bcentral nervous system lupus\b',
    r'\bcentral nervous system lupus vasculitis\b',
    r'\bcentral nervous system systemic lupus erythematosis\b',
    r'\blupus meningoencephalitis\b',
    r'\bneuropsychiatric systemic lupus erythematosus\b',
    r'\bsystemic lupus erythematosis, central nervous system\b',
    r'\bvasospasm, intracranial\b',
    r'\bangiospasm, intracranial\b',
    r'\bcerebral angiospasm\b',
    r'\bcerebral artery spasm\b',
    r'\bcerebral vasospasm\b',
    r'\bcerebrovascular spasm\b',
    r'\bintracranial angiospasm\b',
    r'\bintracranial vascular spasm\b',
    r'\bintracranial vasospasm\b',

    # Cerebrovascular Procedures
    r'\bawake brain surgery\b',
    r'\bbrain stereotactic radiosurgery\b',
    r'\bcarotid angioplasty and stenting\b',
    r'\bcarotid endarterectomy\b',
    r'\bcerebral angiogram\b',
    r'\bcraniotomy\b',
    r'\bct scan\b',
    r'\bembolization therapy\b',
    r'\bepilepsy surgery\b',
    r'\bmicrovascular surgery\b',
    r'\bstereotactic radiosurgery\b',
    r'\bthrombectomy\b',
    r'\btranscarotid artery revascularization\b',
    r'\btcar\b',
    r'\bvascular stenting\b',
    r'\bvertebral artery reconstruction\b',
    r'\bcoiling\b',
    r'\bclipping\b',
    r'\bthrombolysis\b'
]

# Peripheral Arterial Disease Keywords
peripheral_arterial_disease_keywords = [
    # Diseases/Conditions
    r'\bperipheral\b',
    r'\bperipheral artery\b',
    r'\bperipheral arterial\b',
    r'\bperipheral arterial disease\b',
    r'\bperipheral arterial diseases\b',
    r'\bperipheral artery disease\b',
    r'\bpad\b',
    r'\bchronic limb-threatening ischemia\b',
    r'\bclti\b',
    r'\bcritical limb ischemia\b',
    r'\bcli\b',
    r'\bintermittent claudication\b',
    r'\bpad\b',
    r'\bperipheral vascular disease\b',
    r'\blower extremity\b',
    r'\blower extremity arterial disease\b',
    r'\bleg ischemia\b',
    r'\blimb ischemia\b',
    r'\bchronic ischemia\b',
    r'\barteriosclerosis obliterans\b',
    r'\bthromboangiitis obliterans\b',
    r'\bbuerger\'?s disease\b',
    r'\bacute limb ischemia\b',
    r'\bali\b',
    r'\bfoot ulcer\b',
    r'\bdiabetic foot\b',
    r'\bgangrene\b',
    r'\brest pain\b',
    r'\bnon-healing wound\b',

    # Peripheral Arterial Disease Specific Vessel/Location
    r'\biliac artery disease\b',
    r'\biliac artery\b',
    r'\biliac arteries\b',
    r'\biliac stenosis\b',
    r'\biliac occlusion\b',
    r'\bfemoral artery\b',
    r'\bfemoral arteries\b',
    r'\bfemoral artery disease\b',
    r'\bfemoral stenosis\b',
    r'\bfemoral occlusion\b',
    r'\bpopliteal artery\b',
    r'\bpopliteal arteries\b',
    r'\bpopliteal artery disease\b',
    r'\bpopliteal stenosis\b',
    r'\bpopliteal occlusion\b',
    r'\btibial artery\b',
    r'\btibial arteries\b',
    r'\btibial artery disease\b',
    r'\btibial stenosis\b',
    r'\btibial occlusion\b',
    r'\bperoneal artery disease\b',
    r'\bdorsalis pedis artery disease\b',
    r'\brun-off disease\b',
    r'\baortoiliac occlusive disease\b',

    # Peripheral Arterial Disease Procedures
    r'\bangioplasty\b',
    r'\bstents\b',
    r'\bperipheral artery bypass surgery\b',
    r'\baterectomy\b',
    r'\bfemoropopliteal bypass\b',
    r'\bfem-pop bypass\b',
    r'\bfemorodistal bypass\b',
    r'\bfem-tibial bypass\b',
    r'\bfem-peroneal bypass\b',
    r'\bfem-dorsalis pedis bypass\b',
    r'\baortofemoral bypass\b',
    r'\bbypass grafting\b',
    r'\brevascularization\b',
    r'\blimb revascularization\b',
    r'\blimb preservation\b',
    r'\blower extremity revascularization\b',
    r'\blimb salvage\b',
    r'\bthrombolysis\b',
    r'\bthrombectomy\b',
    r'\bembolectomy\b',
    r'\bdrug-coated balloon\b',
    r'\bdcb\b',
    r'\bcovered stent\b',
    r'\bbioabsorbable stent\b',
    r'\bvessel preparation\b',
    r'\bendarterectomy\b',
    r'\bfemoral endarterectomy\b',
    r'\biliac endarterectomy\b',
    r'\bamputation\b',
    r'\bsympathectomy\b',
    r'\bwound care\b',
    
    # Diagnostics often in Peripheral Arterial Disease Procedure Titles
    r'\bperipheral angiography\b',
    r'\bduplex ultrasound\b',
    r'\bankle-brachial index\b',
    r'\babi\b'
]

# Dialysis Access Keywords
dialysis_access_keywords = [
    r'\bhemodiafiltration\b',
    r'\bacetate-free biofiltration\b',
    r'\bbiofiltration, acetate-free\b',
    r'\bhemodialysis\b',
    r'\bhemodialysis, home\b',
    r'\bhome hemodialysis\b',
    r'\brenal dialysis, home\b',
    r'\bperitoneal dialysis\b',
    r'\barteriovenous fistula\b',
    r'\bavf\b',
    r'\baneurysm, arteriovenous\b',
    r'\barteriovenous aneurysm\b',
    r'\barteriovenous fistulas\b',
    r'\bradiocephalic fistula\b',
    r'\bbrachiocephalic fistula\b',
    r'\bbrachiobasilic transposition\b',
    r'\bbasilic vein transposition\b',
    r'\bsnuffbox fistula\b',
    r'\bbuttonhole technique\b',
    r'\barteriovenous shunt, surgical\b',
    r'\bdialysis\b',
    r'\bdialysis access\b',
    r'\barteriovenous graft\b',
    r'\bavg\b',
    r'\bsynthetic graft\b',
    r'\bptfe graft\b',
    r'\bprosthetic graft\b',
    r'\bcentral venous catheter\b',
    r'\bcvc\b',
    r'\bdialysis catheter\b',
    r'\btunneled catheter\b',
    r'\bpermacath\b',
    r'\btemporary catheter\b',
    r'\bnon-tunneled catheter\b',
    
    # Common clinical terms/procedures for Dialysis Access
    r'\bdialysis access dysfunction\b',
    r'\bfistula dysfunction\b',
    r'\bgraft dysfunction\b',
    r'\baccess stenosis\b',
    r'\baccess thrombosis\b',
    r'\bthrombosed fistula\b',
    r'\bthrombosed graft\b',
    r'\bfistula salvage\b',
    r'\bgraft salvage\b',
    r'\baccess infection\b',
    r'\bsteal syndrome\b',
    r'\bdialysis access-induced steal syndrome\b',
    r'\bdais\b',
    r'\baccess aneurysm\b',
    r'\baccess pseudoaneurysm\b',
    r'\bcentral venous stenosis\b',
    r'\bvenous hypertension\b',
    r'\bdialysis access creation\b',
    r'\bfistula creation\b',
    r'\bgraft placement\b',
    r'\bavf creation\b',
    r'\bavg placement\b',
    r'\bdialysis access repair\b',
    r'\bfistuloplasty\b',
    r'\bgraft angioplasty\b',
    r'\baccess thrombectomy\b',
    r'\bfistula thrombectomy\b',
    r'\bgraft thrombectomy\b',
    r'\baccess lysis\b',
    r'\baccess thrombolysis\b',
    r'\bcatheter placement\b',
    r'\bcatheter insertion\b',
    r'\bcatheter exchange\b',
    r'\bcentral venous angioplasty\b',
    r'\bcentral venous stenting\b',
    r'\bvein mapping\b'
]

# Venous and Lymphatic Disease Keywords
venous_lymphatic_keywords = [
    # Venous Disease Terms
    r'\bvenous\b',
    r'\bvenous insufficiency\b',
    r'\bpostphlebitic syndrome\b',
    r'\bpostphlebitic disease\b',
    r'\bpostphlebitic ulcer\b',
    r'\bpostthrombotic syndrome\b',
    r'\bpts\b',
    r'\bvenous stasis syndrome\b',
    r'\bvenous thrombosis\b',
    r'\bdeep vein thrombosis\b',
    r'\bdvt\b',
    r'\bdeep venous thrombosis\b',
    r'\bdeep-vein thrombosis\b',
    r'\bdeep-venous thrombosis\b',
    r'\bphlebothrombosis\b',
    r'\bthrombosis, deep vein\b',
    r'\bthrombosis, venous\b',
    r'\bbudd-chiari syndrome\b',
    r'\bchiari\'?s syndrome\b',
    r'\bhepatic vein thrombosis\b',
    r'\bhepatic venous outflow obstruction\b',
    r'\bretinal vein occlusion\b',
    r'\bbranch retinal vein occlusion\b',
    r'\bbranch vein occlusion\b',
    r'\bcentral retinal vein occlusion\b',
    r'\bretinal branch vein occlusion\b',
    r'\bretinal vein thrombosis\b',
    r'\bthrombosis, retinal vein\b',
    r'\bthrombophlebitis\b',
    r'\bphlegmasia alba dolens\b',
    r'\blemierre syndrome\b',
    r'\blemierre disease\b',
    r'\blemierre\'?s disease\b',
    r'\blemierre\'?s syndrome\b',
    r'\bpostanginal sepsis\b',
    r'\bupper extremity deep vein thrombosis\b',
    r'\bcentral venous catheter thrombosis\b',
    r'\beffort-induced upper extremity deep vein thrombosis\b',
    r'\beffort-related upper extremity deep vein thrombosis\b',
    r'\bexercise-induced upper extremity deep vein thrombosis\b',
    r'\bidiopathic upper extremity deep vein thrombosis\b',
    r'\bpaget-schroetter syndrome\b',
    r'\bupper extremity deep vein thrombosis, primary\b',
    r'\bupper extremity deep vein thrombosis, secondary\b',
    r'\bvaricose veins\b',
    r'\bvarices\b',
    r'\bvarix\b',
    r'\bvaricose ulcer\b',
    r'\bstasis ulcer\b',
    r'\bvenous hypertension ulcers\b',
    r'\bvenous stasis ulcers\b',
    r'\bvenous ulcer\b',
    r'\bphlebitis\b',
    r'\bperiphlebitis\b',
    r'\bsuperior vena cava syndrome\b',
    r'\bchronic venous insufficiency\b',
    r'\bcvi\b',
    r'\bmay-thurner syndrome\b',
    r'\bpelvic congestion syndrome\b',
    r'\bpulmonary embolism\b',
    r'\bpe\b',
    r'\bsuperficial thrombophlebitis\b',
    # Venous general terms
    r'\bvenous disease\b',
    r'\bvenous system\b',
    r'\bvenous reflux\b',
    r'\bvenous hypertension\b',
    r'\bvenous malformation\b', # Different from AVMs

    # Lymphatic Disease Terms
    r'\blymphedema\b',
    r'\bcongenital familial lymphedema\b',
    r'\bcongenital hereditary lymphedema\b',
    r'\bearly onset lymphedema\b',
    r'\bhereditary lymphedema\b',
    r'\bhereditary lymphedema 1\b',
    r'\bhereditary lymphedema type i\b',
    r'\blymphedema, early-onset\b',
    r'\blymphedema, hereditary, ia\b',
    r'\bmilroy disease\b',
    r'\bmilroy\'?s disease\b',
    r'\bnonne-milroy disease\b',
    r'\bnonne-milroy lymphedema\b',
    r'\bnonne-milroy-meige disease\b',
    r'\bprimary congenital lymphedema\b',
    r'\bbreast cancer lymphedema\b',
    r'\bbreast cancer related lymphedema\b',
    r'\bbreast cancer treatment-related lymphedema\b',
    r'\bbreast cancer-related arm lymphedema\b',
    r'\bpost-mastectomy lymphedema\b',
    r'\bpostmastectomy lymphedema\b',
    r'\belephantiasis\b',
    r'\bbigfoot disease\b',
    r'\belephantiasis nostras verrucosa\b',
    r'\bendemic elephantiasis\b',
    r'\bendemic non-filarial elephantiasis\b',
    r'\blymphostatic verrucosis\b',
    r'\bmicrocrystal disease\b',
    r'\bmossy foot\b',
    r'\bpodoconiosis\b',
    r'\belephantiasis, filarial\b',
    r'\bbancroftian elephantiasis\b',
    r'\bbancroftian filariasis\b',
    r'\bbrugian filariasis\b',
    r'\bbrugoa malayi infection\b',
    r'\belephantiasis, bancroftian\b',
    r'\belephantiasis, malayi\b',
    r'\bfilarial elephantiasis\b',
    r'\bfilariasis, lymphatic\b',
    r'\blymphatic filariasis\b',
    r'\bmalayi filariasis\b',
    r'\bwuchereria bancrofti infection\b',
    r'\bnon-filarial lymphedema\b',
    r'\blymphatic diseases\b',
    r'\bhistiocytosis\b',
    r'\bhistiocytic disorders, malignant\b',
    r'\bdendritic cell sarcoma, follicular\b',
    r'\bfollicular dendritic cell sarcoma\b',
    r'\bdendritic cell sarcoma, interdigitating\b',
    r'\binterdigitating cell sarcoma\b',
    r'\binterdigitating dendritic cell sarcoma\b',
    r'\bhistiocytic sarcoma\b',
    r'\bhistiocytosis, malignant\b',
    r'\bmalignant histiocytosis\b',
    r'\btrue histiocytic lymphoma\b',
    r'\btrue malignant histiocytosis\b',
    r'\blangerhans cell sarcoma\b',
    r'\bhistiocytosis, langerhans-cell\b',
    r'\bhand-schueller-christian disease\b',
    r'\bhand-schueller-christian syndrome\b',
    r'\bhand-schüller-christian disease\b',
    r'\bhand-schüller-christian syndrome\b',
    r'\bhashimoto-pritzger disease\b',
    r'\bhistiocytosis x\b',
    r'\bhistiocytosis, generalized\b',
    r'\bhistiocytosis-x\b',
    r'\blangerhans cell granulomatosis\b',
    r'\blangerhans cell granulomatosis, pulmonary\b',
    r'\blangerhans cell histiocytosis\b',
    r'\blangerhans-cell granulomatosis\b',
    r'\blangerhans-cell histiocytosis\b',
    r'\bletterer-siwe disease\b',
    r'\bnon-lipid reticuloendotheliosis\b',
    r'\bpulmonary histiocytosis x\b',
    r'\bpulmonary langerhans cell granulomatosis\b',
    r'\bschueller-christian disease\b',
    r'\bsystemic aleukemic reticuloendotheliosis\b',
    r'\btype 2 histiocytosis\b',
    r'\beosinophilic granuloma\b',
    r'\bhistiocytosis, non-langerhans-cell\b',
    r'\breticulohistiocytoma\b',
    r'\bxanthoma disseminatum\b',
    r'\berdheim-chester disease\b',
    r'\bgranulomatosis, lipid\b',
    r'\bhistiocytosis, sinus\b',
    r'\bdestombes-rosai-dorfman syndrome\b',
    r'\brosai-dorfman disease\b',
    r'\bsinus histiocytosis with massive lymphadenopathy\b',
    r'\blymphohistiocytosis, hemophagocytic\b',
    r'\berythrophagocytic lymphohistiocytosis, familial\b',
    r'\bfamilial erythrophagocytic lymphohistiocytosis\b',
    r'\bfamilial hemophagocytic histiocytosis\b',
    r'\bfamilial hemophagocytic lymphocytosis\b',
    r'\bfamilial hemophagocytic lymphohistiocytosis\b',
    r'\bfamilial hemophagocytic reticulosis\b',
    r'\bfamilial histiocytic reticulosis\b',
    r'\bhemophagocytic lymphohistiocytosis familial -1\b',
    r'\bhemophagocytic lymphohistiocytosis, familial\b',
    r'\bhemophagocytic lymphohistiocytosis, familial, 1\b',
    r'\bhemophagocytic reticulosis, familial\b',
    r'\bhemophagocytic syndrome\b',
    r'\bhemophagocytic syndrome, infection-associated\b',
    r'\bhemophagocytic syndrome, reactive\b',
    r'\bhemophagocytic syndromes\b',
    r'\bprimary hemophagocytic hymphohistiocytosis\b',
    r'\bprimary hemophagocytic lymphohistiocytosis\b',
    r'\breactive hemophagocytic syndrome\b',
    r'\breticulosis, familial histiocytic\b',
    r'\bniemann-pick diseases\b',
    r'\basm deficiency\b',
    r'\basm-deficient niemann-pick disease\b',
    r'\bacid sphingomyelinase deficiency\b',
    r'\bacid sphingomyelinase-deficient niemann-pick disease\b',
    r'\bniemann-pick disease\b',
    r'\bniemann-pick disease, type a\b',
    r'\bclassical niemann-pick disease\b',
    r'\bneuronal cholesterol lipidosis\b',
    r'\bniemann-pick disease, acute neuronopathic form\b',
    r'\bniemann-pick disease, acute neurovisceral form\b',
    r'\bniemann-pick disease, neuronopathic type\b',
    r'\bniemann-pick\'?s disease type a\b',
    r'\bophthalmoplegia, supraoptic vertical\b',
    r'\bsphingomyelin cholesterol lipidosis\b',
    r'\bsphingomyelin lipidosis\b',
    r'\bsphingomyelinase deficiency\b',
    r'\bsphingomyelinase deficiency disease\b',
    r'\btype a niemann-pick disease\b',
    r'\bniemann-pick disease, type b\b',
    r'\bniemann-pick disease, adult non-neuronopathic\b',
    r'\bniemann-pick disease, non-neuronopathic type\b',
    r'\bniemann-pick disease, type e\b',
    r'\bniemann-pick disease, visceral\b',
    r'\bniemann-pick\'?s disease type b\b',
    r'\bniemann-pick\'?s disease type e\b',
    r'\btype b niemann-pick disease\b',
    r'\bniemann-pick disease, type c\b',
    r'\bneurovisceral storage disease with vertical supranuclear ophthalmoplegia\b',
    r'\bniemann-pick disease type c\b',
    r'\bniemann-pick disease type d\b',
    r'\bniemann-pick disease with cholesterol esterification block\b',
    r'\bniemann-pick disease without sphingomyelinase deficiency\b',
    r'\bniemann-pick disease, chronic neuronopathic form\b',
    r'\bniemann-pick disease, nova scotian\b',
    r'\bniemann-pick disease, type c1\b',
    r'\bniemann-pick disease, type d\b',
    r'\bniemann-pick type c disease\b',
    r'\bniemann-pick type d disease\b',
    r'\bniemann-pick disease, subacute juvenile form\b',
    r'\bniemann-pick\'?s disease type c\b',
    r'\bniemann-pick\'?s disease type d\b',
    r'\bnova scotia \(type d\) form of niemann-pick disease\b',
    r'\bnova scotia niemann-pick disease \(type d\)\b',
    r'\bsea-blue histiocyte syndrome\b',
    r'\bhistiocyte syndrome, sea blue\b',
    r'\bhistiocyte syndromes, sea blue\b',
    r'\bhistiocytosis, sea-blue\b',
    r'\bsea blue histiocytosis\b',
    r'\bsea-blue histiocyte disease\b',
    r'\bsea-blue histiocytosis\b',
    r'\bxanthogranuloma, juvenile\b',
    r'\bnevoxanthoendothelioma\b',
    r'\bxanthoma, juvenile\b',
    r'\blymphadenitis\b',
    r'\badenitis\b',
    r'\bcat-scratch disease\b',
    r'\bbartonella henselae infection\b',
    r'\bcat scratch disease\b',
    r'\bcat scratch fever\b',
    r'\bcatscratch disease\b',
    r'\binoculation lymphoreticulosis\b',
    r'\binoculative lymphoreticulosis\b',
    r'\bhistiocytic necrotizing lymphadenitis\b',
    r'\bhistiocytic necrotising lymphadenitis\b',
    r'\bkikuchi disease\b',
    r'\bkikuchi necrotizing lymphadenitis\b',
    r'\bkikuchi\'?s disease\b',
    r'\bkikuchi-fujimoto disease\b',
    r'\bkikuchi-fujimoto\'?s disease\b',
    r'\blymphadenitis, histiocytic necrotizing\b',
    r'\bnosocomial kikuchi\'?s disease\b',
    r'\bkimura disease\b',
    r'\beosinophilic granuloma of soft tissue\b',
    r'\beosinophilic hyperplastic lymphogranuloma\b',
    r'\beosinophilic lymphofollicular granuloma\b',
    r'\beosinophilic lymphofolliculosis\b',
    r'\bkimura\'?s disease\b',
    r'\bmesenteric lymphadenitis\b',
    r'\blymphadenopathy\b',
    r'\badenopathy\b',
    r'\bimmunoblastic lymphadenopathy\b',
    r'\bangioimmunoblastic lymphadenopathy\b',
    r'\blymphadenopathy, immunoblastic\b',
    r'\blymphangiectasis\b',
    r'\blymphangiectasis, intestinal\b',
    r'\bintestinal lymphangiectasis\b',
    r'\blymphangiectasia, intestinal\b',
    r'\blymphangitis\b',
    r'\blymphatic abnormalities\b',
    r'\b22q11 deletion syndrome\b',
    r'\bdigeorge syndrome\b',
    r'\b22q11.2 deletion syndrome\b',
    r'\b22q11.2ds\b',
    r'\bautosomal dominant opitz g-bbb syndrome\b',
    r'\bcatch22\b',
    r'\bconotruncal anomaly face syndrome\b',
    r'\bconotruncal anomaly face syndrome \(ctaf\)\b',
    r'\bdeletion 22q11.2 syndrome\b',
    r'\bdigeorge anomaly\b',
    r'\bdigeorge sequence\b',
    r'\bfamilial third and fourth pharyngeal pouch syndrome\b',
    r'\bhypoplasia of thymus and parathyroids\b',
    r'\bpharyngeal pouch syndrome\b',
    r'\bsedlackova syndrome\b',
    r'\bshprintzen syndrome\b',
    r'\bshprintzen vcf syndrome\b',
    r'\bthird and fourth pharyngeal pouch syndrome\b',
    r'\bthymic aplasia syndrome\b',
    r'\bvcf syndrome\b',
    r'\bvelo-cardio-facial syndrome\b',
    r'\bvelocardiofacial syndrome\b',
    r'\blymphocele\b',
    r'\bcyst, lymphatic\b',
    r'\blymphatic cyst\b',
    r'\blymphatic\b',
    r'\blymphocoele\b',
    r'\blymphoproliferative disorders\b',
    r'\bduncan disease\b',
    r'\bduncan\'?s syndrome\b',
    r'\bepstein-barr virus infection, familial fatal\b',
    r'\bepstein-barr virus-induced lymphoproliferative disease in males\b',
    r'\bfamilial fatal epstein-barr infection\b',
    r'\bimmunodeficiency 5\b',
    r'\bimmunodeficiency, x-linked progressive combined variable\b',
    r'\blymphoproliferative disease, x-linked\b',
    r'\blymphoproliferative syndrome, x-linked, 1\b',
    r'\bpurtilo syndrome\b',
    r'\bx-linked lymphoproliferative disease\b',
    r'\bx-linked lymphoproliferative disorder\b',
    r'\bx-linked lymphoproliferative syndrome\b',
    r'\bagammaglobulinemia\b',
    r'\bhypogammaglobulinemia\b',
    r'\bautoimmune lymphoproliferative syndrome\b',
    r'\bautoimmune lymphoproliferative syndrome type 1, autosomal dominant\b',
    r'\bautoimmune lymphoproliferative syndrome type 2b\b',
    r'\bautoimmune lymphoproliferative syndrome type 2b \(alps2b\)\b',
    r'\bautoimmune lymphoproliferative syndrome, type i, autosomal dominant\b',
    r'\bautoimmune lymphoproliferative syndrome, type iib\b',
    r'\bcanale smith syndrome\b',
    r'\bcanale-smith syndrome\b',
    r'\bcaspase 8 deficiency\b',
    r'\bcaspase-8 deficiency\b',
    r'\bcastleman disease\b',
    r'\bangiofollicular lymph hyperplasia\b',
    r'\bangiofollicular lymph node hyperplasia\b',
    r'\bangiofollicular lymphoid hyperplasia\b',
    r'\bcastleman\'?s disease\b',
    r'\bcastleman\'?s tumor\b',
    r'\bcastlemans disease\b',
    r'\bgiant lymph node hyperplasia\b',
    r'\bhyperplasia, giant lymph node\b',
    r'\blymph node hyperplasia, giant\b',
    r'\bgranuloma\b',
    r'\bgranulomas\b',
    r'\bangiolymphoid hyperplasia with eosinophilia\b',
    r'\bgranuloma, pseudopyogenic\b',
    r'\bpseudopyogenic granuloma\b',
    r'\bchurg-strauss syndrome\b',
    r'\ballergic angiitis\b',
    r'\ballergic angiitis and granulomatosis\b',
    r'\ballergic granulomatosis\b',
    r'\ballergic granulomatous angiitis\b',
    r'\ballergic granulomatous and angiitis\b',
    r'\bangiitis, allergic granulomatous\b',
    r'\begpa disorder\b',
    r'\beosinophilic granulomatosis with polyangiitis\b',
    r'\beosinophilic granulomatous vasculitis\b',
    r'\bgranulomatous allergic angiitis\b',
    r'\bvasculitis, churg-strauss\b',
    r'\bnecrobiotic xanthogranuloma\b',
    r'\bheavy chain disease\b',
    r'\bfranklin disease\b',
    r'\bfranklin\'?s disease\b',
    r'\bgamma-chain disease\b',
    r'\bmu-chain disease\b',
    r'\bimmunoproliferative small intestinal disease\b',
    r'\bheavy chain disease, iga type\b',
    r'\bipsid\b',
    r'\blymphoma, mediterranean\b',
    r'\balpha-chain disease\b',
    r'\binfectious mononucleosis\b',
    r'\binfect mononucleosis\b',
    r'\bleukemia, hairy cell\b',
    r'\bhairy cell leukemia\b',
    r'\bleukemic reticuloendotheliosis\b',
    r'\breticuloendotheliosis, leukemic\b',
    r'\bleukemia, lymphoid\b',
    r'\bleukemia, lymphocytic\b',
    r'\blymphocytic leukemia\b',
    r'\blymphoid leukemia\b',
    r'\bleukemia, b-cell\b',
    r'\bb-cell leukemia\b',
    r'\bb-lymphocytic leukemia\b',
    r'\bleukemia, lymphocytic, b cell\b',
    r'\bleukemia, lymphocytic, b-cell\b',
    r'\blymphocytic leukemia, b-cell\b',
    r'\bleukemia, lymphocytic, chronic, b-cell\b',
    r'\bb-cell chronic lymphocytic leukemia\b',
    r'\bb-cell leukemia, chronic\b',
    r'\bb-cell malignancy, low-grade\b',
    r'\bb-lymphocytic leukemia, chronic\b',
    r'\bchronic lymphocytic leukemia\b',
    r'\bdiffuse well-differentiated lymphocytic lymphoma\b',
    r'\bdisrupted in b-cell malignancy\b',
    r'\bleukemia, b cell, chronic\b',
    r'\bleukemia, b-cell, chronic\b',
    r'\bleukemia, chronic lymphatic\b',
    r'\bleukemia, chronic lymphocytic\b',
    r'\bleukemia, chronic lymphocytic, b-cell\b',
    r'\bleukemia, lymphoblastic, chronic\b',
    r'\bleukemia, lymphocytic, chronic\b',
    r'\bleukemia, lymphocytic, chronic, b cell\b',
    r'\bleukemia, lymphocytic, chronic, b-cell\b',
    r'\blymphoblastic leukemia\b',
    r'\blymphoblastic leukemia, acute\b',
    r'\blymphoblastic leukemia, acute, adult\b',
    r'\blymphoblastic leukemia, acute, childhood\b',
    r'\blymphoblastic leukemia, acute, l1\b',
    r'\blymphoblastic leukemia, acute, l2\b',
    r'\blymphoblastic lymphoma\b',
    r'\blymphocytic leukemia, acute\b',
    r'\blymphocytic leukemia, l1\b',
    r'\blymphocytic leukemia, l2\b',
    r'\blymphoma, lymphoblastic\b',
    r'\bprecursor b-cell lymphoblastic leukemia-lymphoma\b',
    r'\bleukemia, pre-b-cell\b',
    r'\bpre b-all\b',
    r'\bpre-b all\b',
    r'\bpre-b-cell leukemia\b',
    r'\bprecursor b-cell lymphoblastic leukemia\b',
    r'\bprecursor b-cell lymphoblastic lymphoma\b',
    r'\bprecursor t-cell lymphoblastic leukemia-lymphoma\b',
    r'\bleukemia, lymphoblastic, acute, t cell\b',
    r'\bleukemia, lymphoblastic, acute, t-cell\b',
    r'\bleukemia, lymphocytic, acute t cell\b',
    r'\bleukemia, lymphocytic, acute, t-cell\b',
    r'\bleukemia, t-cell, acute\b',
    r'\blymphoblastic leukemia, acute, t cell\b',
    r'\blymphoblastic leukemia, acute, t-cell\b',
    r'\blymphocytic leukemia, t cell, acute\b',
    r'\blymphocytic leukemia, t-cell, acute\b',
    r'\bprecursor t-cell lymphoblastic leukemia\b',
    r'\bprecursor t-cell lymphoblastic lymphoma\b',
    r'\bt-all\b',
    r'\bt-cell acute lymphocytic leukemia\b',
    r'\bt-cell leukemia, acute\b',
    r'\bt-lymphocytic leukemia, acute\b',
    r'\bleukemia, prolymphocytic\b',
    r'\bprolymphocytic leukemia\b',
    r'\bleukemia, prolymphocytic, b-cell\b',
    r'\bb-cell prolymphocytic leukemia\b',
    r'\bleukemia, prolymphocytic, t-cell\b',
    r'\bleukemia, lymphocytic, chronic, t cell\b',
    r'\bleukemia, lymphocytic, chronic, t-cell\b',
    r'\bleukemia, t cell, chronic\b',
    r'\bleukemia, t-cell, chronic\b',
    r'\blymphocytic leukemia, t cell, chronic\b',
    r'\blymphocytic leukemia, t-cell, chronic\b',
    r'\bt-cell leukemia, chronic\b',
    r'\bt-cell prolymphocytic leukemia\b',
    r'\bt-lymphocytic leukemia, chronic\b',
    r'\bleukemia, t-cell\b',
    r'\bleukemia, lymphocytic, t cell\b',
    r'\bleukemia, lymphocytic, t-cell\b',
    r'\blymphocytic leukemia, t-cell\b',
    r'\bt lymphocytic leukemia\b',
    r'\bt-cell leukemia\b',
    r'\bt-lymphocytic leukemia\b',
    r'\bleukemia, large granular lymphocytic\b',
    r'\baggressive nk cell leukemia\b',
    r'\baggressive natural killer cell leukemia\b',
    r'\blgl leukemia\b',
    r'\blarge granular lymphocyte leukemia\b',
    r'\blarge granular lymphocytosis\b',
    r'\bleukemia, lgl\b',
    r'\bleukemia, lymphocytic, large granular\b',
    r'\bleukemia, nk-lgl\b',
    r'\bleukemia, natural killer cell large granular lymphocytic\b',
    r'\bleukemia, t-cell large granular lymphocytic\b',
    r'\bleukemia, t-lgl\b',
    r'\blymphoproliferative disease of granular lymphocytes\b',
    r'\blymphoproliferative disease of large granular lymphocytes\b',
    r'\bnk-cell large granular lymphocytic leukemia\b',
    r'\bnk-lgl leukemia\b',
    r'\bnatural killer cell large granular lymphocytic leukemia\b',
    r'\bt-cell large granular lymphocyte leukemia\b',
    r'\bt-cell large granular lymphocytic leukemia\b',
    r'\bt-lgl leukemia\b',
    r'\bleukemia-lymphoma, adult t-cell\b',
    r'\batll\b',
    r'\bhtlv i associated t cell leukemia lymphoma\b',
    r'\bhtlv-associated leukemia-lymphoma\b',
    r'\bhtlv-i-associated t-cell leukemia-lymphoma\b',
    r'\bhuman t lymphotropic virus associated leukemia lymphoma\b',
    r'\bhuman t lymphotropic virus-associated leukemia-lymphoma\b',
    r'\bhuman t-cell leukemia-lymphoma\b',
    r'\bleukemia lymphoma, adult t cell\b',
    r'\bleukemia lymphoma, t cell, acute, htlv i associated\b',
    r'\bleukemia, adult t-cell\b',
    r'\bleukemia-lymphoma, t-cell, acute, htlv-i-associated\b',
    r'\bt cell leukemia lymphoma, htlv i associated\b',
    r'\bt cell leukemia, adult\b',
    r'\bt-cell leukemia, adult\b',
    r'\bt-cell leukemia-lymphoma, adult\b',
    r'\bt-cell leukemia-lymphoma, htlv-i-associated\b',
    r'\bprecursor cell lymphoblastic leukemia-lymphoma\b',
    r'\ball, childhood\b',
    r'\bacute lymphoblastic leukemia\b',
    r'\bacute lymphoid leukemia\b',
    r'\bleukemia, acute lymphoblastic\b',
    r'\bleukemia, lymphoblastic\b',
    r'\bleukemia, lymphoblastic, acute\b',
    r'\bleukemia, lymphoblastic, acute, l1\b',
    r'\bleukemia, lymphoblastic, acute, l2\b',
    r'\bleukemia, lymphoblastic, acute, philadelphia-positive\b',
    r'\bleukemia, lymphocytic, acute\b',
    r'\bleukemia, lymphocytic, acute, l1\b',
    r'\bleukemia, lymphocytic, acute, l2\b',
    r'\bleukemia, lymphoid, acute\b',
    r'\blymphoblastic leukemia\b',
    r'\blymphoblastic leukemia, acute\b',
    r'\blymphoblastic leukemia, acute, adult\b',
    r'\blymphoblastic leukemia, acute, childhood\b',
    r'\blymphoblastic leukemia, acute, l1\b',
    r'\blymphoblastic leukemia, acute, l2\b',
    r'\blymphoblastic lymphoma\b',
    r'\blymphocytic leukemia, acute\b',
    r'\blymphocytic leukemia, l1\b',
    r'\blymphocytic leukemia, l2\b',
    r'\blymphoma, lymphoblastic\b',
    r'\bprecursor b-cell lymphoblastic leukemia-lymphoma\b',
    r'\bleukemia, pre-b-cell\b',
    r'\bpre b-all\b',
    r'\bpre-b all\b',
    r'\bpre-b-cell leukemia\b',
    r'\bprecursor b-cell lymphoblastic leukemia\b',
    r'\bprecursor b-cell lymphoblastic lymphoma\b',
    r'\bprecursor t-cell lymphoblastic leukemia-lymphoma\b',
    r'\bleukemia, lymphoblastic, acute, t cell\b',
    r'\bleukemia, lymphoblastic, acute, t-cell\b',
    r'\bleukemia, lymphocytic, acute t cell\b',
    r'\bleukemia, lymphocytic, acute, t-cell\b',
    r'\bleukemia, t-cell, acute\b',
    r'\blymphoblastic leukemia, acute, t cell\b',
    r'\blymphoblastic leukemia, acute, t-cell\b',
    r'\blymphocytic leukemia, t cell, acute\b',
    r'\blymphocytic leukemia, t-cell, acute\b',
    r'\bprecursor t-cell lymphoblastic leukemia\b',
    r'\bprecursor t-cell lymphoblastic lymphoma\b',
    r'\bt-all\b',
    r'\bt-cell acute lymphocytic leukemia\b',
    r'\bt-cell leukemia, acute\b',
    r'\bt-lymphocytic leukemia, acute\b',
    r'\blymphangiomyoma\b',
    r'\blymphangioleiomyoma\b',
    r'\blymphangioleiomyomatosis\b',
    r'\blymphangiomyomatosis\b',
    r'\blymphoma\b',
    r'\bgerminoblastoma\b',
    r'\blymphoma, malignant\b',
    r'\breticulolymphosarcoma\b',
    r'\bsarcoma, germinoblastic\b',
    r'\bcomposite lymphoma\b',
    r'\bhodgkin disease\b',
    r'\bgranuloma, hodgkin\b',
    r'\bgranuloma, hodgkin\'?s\b',
    r'\bgranuloma, hodgkins\b',
    r'\bgranuloma, malignant\b',
    r'\bhodgkin lymphoma\b',
    r'\bhodgkin lymphoma, adult\b',
    r'\bhodgkin\'?s disease\b',
    r'\bhodgkin\'?s lymphoma\b',
    r'\bhodgkins disease\b',
    r'\blymphocyte depletion hodgkin\'?s lymphoma\b',
    r'\blymphocyte-rich classical hodgkin\'?s lymphoma\b',
    r'\blymphogranuloma, malignant\b',
    r'\bmixed cellularity hodgkin\'?s lymphoma\b',
    r'\bnodular lymphocyte-predominant hodgkin\'?s lymphoma\b',
    r'\bnodular sclerosing hodgkin\'?s lymphoma\b',
    r'\bintraocular lymphoma\b',
    r'\blymphoma, non-hodgkin\b',
    r'\bdiffuse mixed small and large cell lymphoma\b',
    r'\bdiffuse mixed-cell lymphoma\b',
    r'\bdiffuse small cleaved-cell lymphoma\b',
    r'\bdiffuse undifferentiated lymphoma\b',
    r'\blymphatic sarcoma\b',
    r'\blymphoma, atypical diffuse small lymphoid\b',
    r'\blymphoma, diffuse\b',
    r'\blymphoma, diffuse, mixed lymphocytic-histiocytic\b',
    r'\blymphoma, high-grade\b',
    r'\blymphoma, intermediate-grade\b',
    r'\blymphoma, low-grade\b',
    r'\blymphoma, mixed\b',
    r'\blymphoma, mixed cell, diffuse\b',
    r'\blymphoma, mixed lymphocytic-histiocytic\b',
    r'\blymphoma, mixed small and large cell, diffuse\b',
    r'\blymphoma, mixed-cell\b',
    r'\blymphoma, mixed-cell, diffuse\b',
    r'\blymphoma, non-hodgkin\'?s\b',
    r'\blymphoma, non-hodgkin, familial\b',
    r'\blymphoma, non-hodgkins\b',
    r'\blymphoma, nonhodgkin\'?s\b',
    r'\blymphoma, nonhodgkins\b',
    r'\blymphoma, pleomorphic\b',
    r'\blymphoma, small cleaved cell, diffuse\b',
    r'\blymphoma, small cleaved-cell, diffuse\b',
    r'\blymphoma, small non-cleaved-cell\b',
    r'\blymphoma, small noncleaved-cell\b',
    r'\blymphoma, small and large cleaved-cell, diffuse\b',
    r'\blymphoma, undifferentiated\b',
    r'\blymphoma, undifferentiated, diffuse\b',
    r'\blymphosarcoma\b',
    r'\bmixed small and large cell lymphoma, diffuse\b',
    r'\bmixed-cell lymphoma\b',
    r'\bmixed-cell lymphoma, diffuse\b',
    r'\bnon-hodgkin lymphoma\b',
    r'\bnon-hodgkin\'?s lymphoma\b',
    r'\breticulosarcoma\b',
    r'\breticulum cell sarcoma\b',
    r'\breticulum-cell sarcoma\b',
    r'\bsarcoma, lymphatic\b',
    r'\bsarcoma, reticulum-cell\b',
    r'\bsmall cleaved-cell lymphoma, diffuse\b',
    r'\bsmall non-cleaved-cell lymphoma\b',
    r'\bsmall noncleaved-cell lymphoma\b',
    r'\bundifferentiated lymphoma\b',
    r'\bmarek disease\b',
    r'\bfowl paralysis\b',
    r'\bmarek\'?s disease\b',
    r'\bsarcoidosis\b',
    r'\bbesnier-boeck disease\b',
    r'\bbesnier-boeck-schaumann syndrome\b',
    r'\bboeck disease\b',
    r'\bboeck\'?s disease\b',
    r'\bboeck\'?s sarcoid\b',
    r'\bschaumann disease\b',
    r'\bschaumann syndrome\b',
    r'\bschaumann\'?s syndrome\b',
    r'\bsarcoidosis, pulmonary\b',
    r'\bpulmonary sarcoidosis\b',
    r'\buveoparotid fever\b',
    r'\bheerfordt syndrome\b',
    r'\buveoparotitis\b',
    r'\bsezary syndrome\b',
    r'\berythroderma, sezary\b',
    r'\bsezary\'?s lymphoma\b',
    r'\btumor lysis syndrome\b',
    r'\btumour lysis syndrome\b',
    r'\bwaldenstrom macroglobulinemia\b',
    r'\bfamilial waldenstrom\'?s macroglobulinaemia\b',
    r'\blymphoma, lymphocytic, plasmacytoid\b',
    r'\blymphoma, lymphoplasmacytoid\b',
    r'\bmacroglobulinemia\b',
    r'\bprimary macroglobulinemia\b',
    r'\bwaldenstrom\'?s macroglobulinaemia\b',
    r'\bwaldenstrom\'?s macroglobulinemia\b',
    r'\bmucocutaneous lymph node syndrome\b',
    r'\bkawasaki disease\b',
    r'\bkawasaki syndrome\b',
    r'\blymph node syndrome, mucocutaneous\b',
    r'\bpseudolymphoma\b',
    r'\bhyperplasia, reactive lymphoid\b',
    r'\blymphocytoma\b',
    r'\blymphoid hyperplasia, reactive\b',
    r'\bsplenic diseases\b',
    r'\bheterotaxy syndrome\b',
    r'\basplenia syndrome\b',
    r'\basplenia with cardiovascular anomalies\b',
    r'\bivemark syndrome\b',
    r'\bleft atrial isomerism\b',
    r'\bleft atrial isomerism with polysplenia\b',
    r'\bpolysplenia syndrome\b',
    r'\bright atrial isomerism\b',
    r'\bright atrial isomerism with asplenia\b',
    r'\bsitus ambiguus\b',
    r'\bsitus ambiguus viscerum\b',
    r'\bsitus ambiguus with asplenia\b',
    r'\bsitus ambiguus with polysplenia\b',
    r'\bvisceral heterotaxy\b',
    r'\bhypersplenism\b',
    r'\banemia, splenic\b',
    r'\bsplenic infarction\b',
    r'\binfarct of the spleen\b',
    r'\bsplenic infarct\b',
    r'\bsplenic infarcts\b',
    r'\bsplenic neoplasms\b',
    r'\bcancer of spleen\b',
    r'\bcancer of the spleen\b',
    r'\bneoplasms, splenic\b',
    r'\bspleen cancer\b',
    r'\bspleen neoplasms\b',
    r'\bsplenic cancer\b',
    r'\bsplenic rupture\b',
    r'\bsplenosis\b',
    r'\btuberculosis, splenic\b',
    r'\bwandering spleen\b',
    r'\bdisplaced spleen\b',
    r'\bdrifting spleen\b',
    r'\bfloating spleen\b',
    r'\bsplenic ptosis\b',
    r'\bsplenoptosis\b',
    r'\bthymus hyperplasia\b',
    r'\bhyperplasia of thymus gland\b',
    r'\bthymic hyperplasia\b',
    r'\bthymus neoplasms\b',
    r'\bcancer of thymus\b',
    r'\bcancer of the thymus\b',
    r'\bneoplasms, thymic\b',
    r'\bneoplasms, thymus\b',
    r'\bthymic cancer\b',
    r'\bthymic neoplasms\b',
    r'\bthymic tumors\b',
    r'\bthymus cancer\b',
    r'\bthymus tumors\b',
    r'\bthymoma\b',
    r'\bcarcinoma, thymic\b',
    r'\blymphatic vessels\b',
    r'\bcapillaries, lymphatic\b',
    r'\blymphatic capillaries\b',
    r'\blymphatic venules\b',
    r'\bvenules, lymphatic\b',
    r'\bendothelium, lymphatic\b',
    r'\blymphatic endothelium\b',
    r'\bthoracic duct\b',
    r'\bcisterna chyli\b',
    r'\blymphangioma\b',
    r'\bendothelioma, lymphatic\b',
    r'\blymphangioendothelioma\b',
    r'\blymphangioma, cavernous\b',
    r'\blymphangioma, cystic\b',
    r'\bcystic hygroma colli\b',
    r'\bhygroma\b',
    r'\bhygroma, cystic\b',
    r'\bnutcracker\b',
    r'\bnutcracker syndrome\b',

    # Venous and Lymphatic Disease Procedures
    r'\bambulatory phlebectomy\b',
    r'\bhigh ligation and vein stripping\b',
    r'\bsclerotherapy\b',
    r'\bcatheter-directed thrombolytic therapy\b',
    r'\banticoagulation\b',
    r'\bangioplasty\b',
    r'\bendovenous thermal ablation\b',
    r'\bvena cava filter\b',
    r'\bseps\b',
    r'\bsubfascial endoscopic perforator surgery\b',
    r'\bsurgical bypass\b',
    r'\blymphaticovenous anastomosis\b',
    r'\blva\b',
    r'\bvascularized lymph node transfer\b',
    r'\bvln\b',
    r'\blymphatic bypass\b',
    r'\bdebulking\b',
    r'\bliposuction\b',
    r'\bsurgical excision for lymphatic malformations\b',
    r'\blymphoscintigraphy\b',
    r'\bicg lymphography\b',
    r'\bindocyanine green lymphography\b',
    r'\bmicrosurgery for lymphatic procedures\b',
    r'\bvenous thrombectomy\b',
    r'\bvenous stenting\b',
    r'\bvenous angioplasty\b',
    r'\bligation and stripping\b',
    r'\bvein stripping\b',
    r'\bradiofrequency ablation\b',
    r'\blaser ablation\b',
    r'\bivc filter retrieval\b',
    r'\bivc filter placement\b',
    r'\blymphedema management\b',
    r'\bcdt\b',
    r'\bcomplete decongestive therapy\b'
]


# Keywords Dictionary
ALL_KEYWORDS = {
    'Aortic Disease': [re.compile(pattern) for pattern in aortic_keywords],
    'Cerebrovascular Disease': [re.compile(pattern) for pattern in cerebrovascular_keywords],
    'Peripheral Arterial Disease': [re.compile(pattern) for pattern in peripheral_arterial_disease_keywords],
    'Dialysis Access': [re.compile(pattern) for pattern in dialysis_access_keywords],
    'Venous and Lymphatic Disease': [re.compile(pattern) for pattern in venous_lymphatic_keywords]
}

# Categorization Function
def categorize_title(title, debug=False):
    if not isinstance(title, str):
        return 'Other' # Non-string titles

    title_lower = title.lower()
    matched_categories = []

    if debug:
        print(f"Checking title: '{title_lower}'")

    for category_name, patterns in ALL_KEYWORDS.items():
        category_matched = False
        for pattern in patterns:
            if pattern.search(title_lower):
                matched_categories.append(category_name)
                if debug:
                    print(f"  ✓ Matched '{category_name}' with pattern: {pattern.pattern}")
                category_matched = True
                break # When it finds a match for this category, move to next category
        
        if debug and not category_matched:
            print(f"  ✗ No match for '{category_name}'")

    # Removes duplicates from matched_categories
    matched_categories = list(set(matched_categories))

    if len(matched_categories) == 1:
        return matched_categories[0] # Clear winner
    elif len(matched_categories) > 1:
        # Sorts for consistent 'Uncertain' output
        matched_categories.sort()
        return 'Uncertain: ' + ', '.join(matched_categories)
    else:
        return 'Other' # No keywords found for defined category

# Main Script Execution
if __name__ == "__main__":
    input_csv_filename = 'vamtitles.csv'  # RENAME TO CSV FILE NAME
    output_csv_filename = 'categorized_vam_titles.csv' # RENAME OUTPUT FILE TO NAME OF MEETING

    # To check if the input file exists
    if not os.path.exists(input_csv_filename):
        print(f"Error: Input file '{input_csv_filename}' not found.")
        print("Export Google Sheet as a CSV and place it in same directory.")
        print("Don't forget to rename the file to match 'input_csv_filename' in the script.")
    else:
        print(f"Loading titles from '{input_csv_filename}'...")
        try:

            df = pd.read_csv(input_csv_filename)
            
            title_column_name = 'Title' # MAKE SURE TITLE COLUMN HAS THIS NAME

            if title_column_name not in df.columns:
                print(f"Error: Column '{title_column_name}' not found in CSV.")
                print("Please check CSV file's column names or adjust 'title_column_name' in the script.")
            else:
                print("Categorizing titles...")
                df['Vascular Disease Category'] = df[title_column_name].apply(categorize_title)

                # Saves the results to a new CSV
                df.to_csv(output_csv_filename, index=False)
                print(f"Categorization complete! Results saved to '{output_csv_filename}'")
                print("\nHere's a preview of the categorization:")
                print(df[[title_column_name, 'Vascular Disease Category']].head(10)) # Shows first 10 rows

                print("\nValue counts for the 'Vascular Disease Category':")
                print(df['Vascular Disease Category'].value_counts())

        except Exception as e:
            print(f"An error occurred during file processing: {e}")
            print("Please ensure your CSV file is correctly formatted and not open in another program.")
